name: python-ml
dependencies:
  - python==3.5.2
  - numpy==1.11.1
  - scipy==0.17.1
  - scikit-learn==0.18
  - matplotlib>1.5
  - pandas==0.18.1
  - pillow
  - graphviz
  - python-graphviz
  - imageio
  - joblib
